#!/usr/bin/env ruby

require 'httpclient'
require 'json'

username = ARGV[0]

raise "missing username" unless username

begin
    Dir.mkdir("lib/staging")
rescue 
end

File.write("lib/staging/repo_names", nil)

def get_repo_names username

	req = HTTPClient.new
	result = []
	page = 0

	loop do
		page += 1
		p "fetching page #{page}"
		res = req.get "https://api.github.com/users/#{username}/repos?page=#{page}&per_page=100"
		repos = JSON.parse(res.body)
		raise 'No results found, check username' if repos.class == Hash && repos["message"] == "Not Found"
		break if repos.empty?
		result += repos.map { |repo| repo_name(repo["git_url"]) }.select { |name| true }
	end

	result
end

def repo_name git_url
	git_url.split("/").last.split(".").first
end

File.write("lib/staging/repo_names", get_repo_names(username).join("\n"))



