#!/usr/bin/env ruby

require ("selenium-webdriver")

username = ARGV[0]
URL = "https://github.com/#{username}/"

driver = Selenium::WebDriver.for :firefox

driver.navigate_to URL

File.readlines("staging/repo_names").each do |repo|
	driver.navigate_to URL + "/#{repo}/settings"
	driver.find_elements(class: "btn btn-danger boxed-action", )
	debugger
end